# Generated by Django 2.2.10 on 2020-06-09 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_application_school_other'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='agree_to_mlh_privacy',
            field=models.BooleanField(choices=[(True, 'Agree')], default=None),
        ),
    ]
