# Generated by Django 2.2.10 on 2020-06-14 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_application_agree_to_mlh_privacy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='transport_needed',
        ),
    ]
