# Generated by Django 2.2.10 on 2020-06-14 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_remove_application_transport_needed'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='devpost_link',
            field=models.URLField(blank=True, max_length=255, verbose_name='Your Devpost'),
        ),
        migrations.AddField(
            model_name='application',
            name='github_link',
            field=models.URLField(blank=True, max_length=255, verbose_name='Your GitHub'),
        ),
        migrations.AddField(
            model_name='application',
            name='instagram_link',
            field=models.URLField(blank=True, max_length=255, verbose_name='Your Instagram'),
        ),
        migrations.AddField(
            model_name='application',
            name='linkedin_link',
            field=models.URLField(blank=True, max_length=255, verbose_name='Your Linkedin'),
        ),
        migrations.AddField(
            model_name='application',
            name='personal_website_link',
            field=models.URLField(blank=True, max_length=255, verbose_name='Your Website'),
        ),
    ]
