# Generated by Django 2.2.10 on 2020-06-17 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_auto_20200614_1449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='agree_to_coc',
        ),
        migrations.RemoveField(
            model_name='application',
            name='agree_to_mlh_privacy',
        ),
        migrations.RemoveField(
            model_name='application',
            name='dietary_restrictions',
        ),
        migrations.RemoveField(
            model_name='application',
            name='travel_reimbursement',
        ),
        migrations.AddField(
            model_name='application',
            name='advertising',
            field=models.CharField(choices=[('University Email', 'University Email'), ('Facebook/Instagram', 'Facebook / Instagram'), ('Friend', 'A Friend'), ('MLH', 'MLH Website / Newsletter'), ('MSC', 'MSC Open House'), ('On Campus', 'Campus Marketing (E.g. Flyers, Posters, Whiteboards, etc)')], default=None, max_length=22, verbose_name='How did you hear about us?'),
        ),
        migrations.AddField(
            model_name='application',
            name='age',
            field=models.IntegerField(default=None, verbose_name='What is your age?'),
        ),
        migrations.AddField(
            model_name='application',
            name='agree_to_data_sharing',
            field=models.BooleanField(choices=[(True, 'Agree')], default=None, help_text='We need your authorization to share your application/registration information for event administration, ranking, MLH administration, pre and post-event informational e-mails, and occasional messages about hackathons, in-line with the MLH Privacy Policy.'),
        ),
        migrations.AddField(
            model_name='application',
            name='agree_to_mlh_policies',
            field=models.BooleanField(choices=[(True, 'Agree')], default=None, help_text='Being an MLH event, we need participants to be familiar with the MLH Code of Conduct and the MLH Contest Terms and Conditions.'),
        ),
        migrations.AddField(
            model_name='application',
            name='datascience_experience',
            field=models.TextField(default=None, max_length=500),
        ),
        migrations.AddField(
            model_name='application',
            name='first_generation',
            field=models.BooleanField(choices=[(True, 'Agree')], default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='learner_pack',
            field=models.BooleanField(choices=[(True, 'Agree')], default=None, help_text='Learners will recieve priority admission to learner classes, be assigned a dedicated mentor, and have access to learner specific challenges/prizes.'),
        ),
        migrations.AddField(
            model_name='application',
            name='minor',
            field=models.TextField(default=None, max_length=500, verbose_name="What's your minor(s)?"),
        ),
        migrations.AddField(
            model_name='application',
            name='physical_location',
            field=models.CharField(default=None, max_length=20, verbose_name='Where will you be participating from?'),
        ),
        migrations.AddField(
            model_name='application',
            name='technology_experience',
            field=models.TextField(default=None, max_length=500),
        ),
        migrations.AddField(
            model_name='application',
            name='volunteer_interest',
            field=models.CharField(choices=[(True, 'Yes'), (False, 'No')], default='None', max_length=22, verbose_name='Would you be interested in volunteering/mentoring for part of the event?'),
        ),
        migrations.AlterField(
            model_name='application',
            name='devpost_link',
            field=models.URLField(blank=True, default=None, max_length=255, verbose_name='Your Devpost'),
        ),
        migrations.AlterField(
            model_name='application',
            name='extra_links',
            field=models.CharField(blank=True, max_length=200, verbose_name="Point us to anything else you'd like us to look at while considering your application"),
        ),
        migrations.AlterField(
            model_name='application',
            name='github_link',
            field=models.URLField(blank=True, default=None, max_length=255, verbose_name='Your GitHub'),
        ),
        migrations.AlterField(
            model_name='application',
            name='instagram_link',
            field=models.URLField(blank=True, default=None, max_length=255, verbose_name='Your Instagram'),
        ),
        migrations.AlterField(
            model_name='application',
            name='linkedin_link',
            field=models.URLField(blank=True, default=None, max_length=255, verbose_name='Your Linkedin'),
        ),
        migrations.AlterField(
            model_name='application',
            name='major',
            field=models.TextField(default=None, max_length=500, verbose_name="What's your major(s)?"),
        ),
        migrations.AlterField(
            model_name='application',
            name='personal_website_link',
            field=models.URLField(blank=True, default=None, max_length=255, verbose_name='Your Website'),
        ),
        migrations.AlterField(
            model_name='application',
            name='question1',
            field=models.TextField(max_length=500, verbose_name='What prize do you want to see at TD?'),
        ),
        migrations.AlterField(
            model_name='application',
            name='question2',
            field=models.TextField(max_length=500, verbose_name='What workshops do you want to see at TD?'),
        ),
        migrations.AlterField(
            model_name='application',
            name='question3',
            field=models.TextField(max_length=500, verbose_name='Have you taken any data science / CS related classes?'),
        ),
    ]
